services:
  dev:
    build:
      context:  .
      dockerfile: DockerfileDev
    container_name: online-belote-dev
    image: online-belote:dev
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    stdin_open:  true
    tty: true

  prod:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://localhost:8082
    container_name: online-belote-prod
    image: online-belote:prod
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production