/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as JoinRouteImport } from './routes/join'
import { Route as CreateRouteImport } from './routes/create'
import { Route as LobbyRouteRouteImport } from './routes/lobby/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LobbyResultsRouteImport } from './routes/lobby/results'
import { Route as LobbyLobbyIdWaitingRouteImport } from './routes/lobby/$lobbyId/waiting'

const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const LobbyRouteRoute = LobbyRouteRouteImport.update({
  id: '/lobby',
  path: '/lobby',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LobbyResultsRoute = LobbyResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => LobbyRouteRoute,
} as any)
const LobbyLobbyIdWaitingRoute = LobbyLobbyIdWaitingRouteImport.update({
  id: '/$lobbyId/waiting',
  path: '/$lobbyId/waiting',
  getParentRoute: () => LobbyRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lobby': typeof LobbyRouteRouteWithChildren
  '/create': typeof CreateRoute
  '/join': typeof JoinRoute
  '/lobby/results': typeof LobbyResultsRoute
  '/lobby/$lobbyId/waiting': typeof LobbyLobbyIdWaitingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lobby': typeof LobbyRouteRouteWithChildren
  '/create': typeof CreateRoute
  '/join': typeof JoinRoute
  '/lobby/results': typeof LobbyResultsRoute
  '/lobby/$lobbyId/waiting': typeof LobbyLobbyIdWaitingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/lobby': typeof LobbyRouteRouteWithChildren
  '/create': typeof CreateRoute
  '/join': typeof JoinRoute
  '/lobby/results': typeof LobbyResultsRoute
  '/lobby/$lobbyId/waiting': typeof LobbyLobbyIdWaitingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/lobby'
    | '/create'
    | '/join'
    | '/lobby/results'
    | '/lobby/$lobbyId/waiting'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/lobby'
    | '/create'
    | '/join'
    | '/lobby/results'
    | '/lobby/$lobbyId/waiting'
  id:
    | '__root__'
    | '/'
    | '/lobby'
    | '/create'
    | '/join'
    | '/lobby/results'
    | '/lobby/$lobbyId/waiting'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LobbyRouteRoute: typeof LobbyRouteRouteWithChildren
  CreateRoute: typeof CreateRoute
  JoinRoute: typeof JoinRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lobby': {
      id: '/lobby'
      path: '/lobby'
      fullPath: '/lobby'
      preLoaderRoute: typeof LobbyRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lobby/results': {
      id: '/lobby/results'
      path: '/results'
      fullPath: '/lobby/results'
      preLoaderRoute: typeof LobbyResultsRouteImport
      parentRoute: typeof LobbyRouteRoute
    }
    '/lobby/$lobbyId/waiting': {
      id: '/lobby/$lobbyId/waiting'
      path: '/$lobbyId/waiting'
      fullPath: '/lobby/$lobbyId/waiting'
      preLoaderRoute: typeof LobbyLobbyIdWaitingRouteImport
      parentRoute: typeof LobbyRouteRoute
    }
  }
}

interface LobbyRouteRouteChildren {
  LobbyResultsRoute: typeof LobbyResultsRoute
  LobbyLobbyIdWaitingRoute: typeof LobbyLobbyIdWaitingRoute
}

const LobbyRouteRouteChildren: LobbyRouteRouteChildren = {
  LobbyResultsRoute: LobbyResultsRoute,
  LobbyLobbyIdWaitingRoute: LobbyLobbyIdWaitingRoute,
}

const LobbyRouteRouteWithChildren = LobbyRouteRoute._addFileChildren(
  LobbyRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LobbyRouteRoute: LobbyRouteRouteWithChildren,
  CreateRoute: CreateRoute,
  JoinRoute: JoinRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
